# MEMBER 5's Code (Danny) — data access.
# Merges: data_v2/inbox (raw emails) + root submission.json (pipeline)
#         + outputs/reviews.json (human decisions).
# Makes no AI calls, so running the console costs no tokens.

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import escalation

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data_v2"
OUT = ROOT / "outputs"

# Primary source is now the root submission.json generated by pipeline.py
SUBMISSION_PATH = ROOT / "submission.json"
RESULTS_PATH = ROOT / "submission.json"
REVIEWS_PATH = OUT / "reviews.json"

FIELDS = ["shipper", "consignee", "notify_party", "port_of_loading",
          "port_of_discharge", "container_count", "gross_weight_kg"]

FIELD_LABELS = {
    "shipper": "Shipper", "consignee": "Consignee", "notify_party": "Notify party",
    "port_of_loading": "Port of loading", "port_of_discharge": "Port of discharge",
    "container_count": "Container count", "gross_weight_kg": "Gross weight",
}
CATEGORY_LABELS = {
    "BL_COMPARISON": "Document comparison", "SI_REQUEST": "New SI request",
    "INVOICE_QUERY": "Invoice query", "GENERAL": "General", "SPAM": "Spam",
    None: "Not classified",
}
REASON_LABELS = escalation.REASONS


def _load(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return default


def _save(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def read_inbox() -> List[Dict[str, Any]]:
    d = DATA / "inbox"
    if not d.exists():
        return []
    return [json.loads(p.read_text(encoding="utf-8"))
            for p in sorted(d.glob("email_*.json"))]


def read_attachment(rel_path: str) -> Optional[str]:
    """Plain text only. Binary formats belong to the extractor."""
    p = DATA / rel_path
    if not p.exists() or p.suffix.lower() != ".txt":
        return None
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def pipeline_has_run() -> bool:
    # Checks root submission.json first, then fallback to outputs/results.json
    return SUBMISSION_PATH.exists() or (OUT / "results.json").exists()


def load_cases() -> List[Dict[str, Any]]:
    # Load pipeline output from root submission.json, or fallback to outputs/results.json
    results = _load(SUBMISSION_PATH, {})
    if not results:
        results = _load(OUT / "results.json", {})

    reviews = _load(REVIEWS_PATH, {})
    cases = []
    
    inbox_emails = read_inbox()
    if inbox_emails:
        for email in inbox_emails:
            eid = email["email_id"]
            c = dict(results.get(eid, {}))
            c["email_id"] = eid
            c["subject"] = email.get("subject", "")
            c["from"] = email.get("from", "")
            c["attachments"] = email.get("attachments", [])
            c.setdefault("category", None)
            c.setdefault("decided_by", None)
            c.setdefault("status", "PENDING")
            c.setdefault("review_reason", None)
            c.setdefault("has_defect", False)
            c.setdefault("defect_fields", [])
            c.setdefault("fields", {})
            c.setdefault("error", None)
            decision = reviews.get(eid)
            if decision:
                c = escalation.apply_decision(c, decision["decision"],
                                              decision.get("reviewer", "reviewer"))
                c["reviewed_at"] = decision.get("at")
                c["reviewer_note"] = decision.get("note")
            cases.append(c)
    else:
        # Fallback if raw inbox folder is not present on disk
        for eid, res in results.items():
            c = dict(res)
            c["email_id"] = eid
            c.setdefault("subject", f"Email {eid}")
            c.setdefault("from", "")
            c.setdefault("attachments", [])
            c.setdefault("fields", {})
            decision = reviews.get(eid)
            if decision:
                c = escalation.apply_decision(c, decision["decision"],
                                              decision.get("reviewer", "reviewer"))
                c["reviewed_at"] = decision.get("at")
                c["reviewer_note"] = decision.get("note")
            cases.append(c)

    return cases


def save_decision(email_id: str, decision: str, reviewer: str = "reviewer", note: Optional[str] = None) -> None:
    reviews = _load(REVIEWS_PATH, {})
    reviews[email_id] = {
        "decision": decision, "reviewer": reviewer, "note": note,
        "at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    _save(REVIEWS_PATH, reviews)


def clear_decision(email_id: str) -> None:
    reviews = _load(REVIEWS_PATH, {})
    reviews.pop(email_id, None)
    _save(REVIEWS_PATH, reviews)


def export_submission(cases: List[Dict[str, Any]]) -> int:
    """The file the scorer reads, carrying every human decision."""
    submission = {}
    for c in cases:
        status = c["status"]
        if status in ("PENDING", "FAILED"):
            status = "NEEDS_REVIEW"
        submission[c["email_id"]] = {
            "category": c.get("category") or "GENERAL",
            "status": status,
            "review_reason": c.get("review_reason"),
            "has_defect": bool(c.get("has_defect")),
            "defect_fields": c.get("defect_fields", []),
        }
    
    # Save both to the root submission.json and outputs/submission.json
    _save(SUBMISSION_PATH, submission)
    _save(OUT / "submission.json", submission)
    return len(submission)


def summary(cases: List[Dict[str, Any]]) -> Dict[str, Any]:
    by_status, by_category, by_reason = {}, {}, {}
    for c in cases:
        by_status[c["status"]] = by_status.get(c["status"], 0) + 1
        if c.get("category"):
            by_category[c["category"]] = by_category.get(c["category"], 0) + 1
        if c.get("review_reason"):
            by_reason[c["review_reason"]] = by_reason.get(c["review_reason"], 0) + 1
    return {"total": len(cases), "by_status": by_status,
            "by_category": by_category, "by_reason": by_reason,
            "reviewed": sum(1 for c in cases if c.get("reviewed_by"))}